name: BlockyGroups
main: com.blockycraft.blockygroups.BlockyGroups
version: 1.0.0
author: Bernardo Zukerman
description: Plugin de grupos com integracao ao BlockyClaim.
softdepend: [BlockyGeoIP]
permissions:
  blockygroups.grp:
    description: Permite o uso de todos os comandos do /grp.
    default: true
commands:
  grp:
    description: Comando principal para gerenciar grupos.
    usage: /grp [pagina]
    permission: blockygroups.grp
    aliases: [f, grupo, grupo]
  gc:
    description: Envia uma mensagem apenas para membros da sua grupo.
    usage: /gc <mensagem>
    permission: blockygroups.grp
    aliases: [cg]
