name: BlockyFactions
main: com.blockycraft.blockyfactions.BlockyFactions
version: 1.0.0
author: Bernardo Zukerman
description: Plugin de faccoes com integracao ao BlockyClaim.

commands:
  fac:
    description: Comando principal para gerenciar faccoes.
    usage: /fac <ajuda>